### ISSUE TITLE
Script fails when run in docker container on Jenkins

### ISSUE THREAD

**Issue by hikkamorii** [blackducksoftware/import_yocto_bm#13]
Hi. I've been trying to to troubleshoot this issue for days with no success.

When I run the script inside docker container on my local machine, everything works as expected, I get:
```
- Processing layers: ...
- Processing recipes: ...

Uploading scan to Black Duck server ...
Scan file uploaded successfully
Black Duck project '[redacted]' created.
```

However when ran in the same docker container, but under Jenkins, the result I get is:
```
- Processing layers: ...
- Processing recipes: ...

Uploading scan to Black Duck server ...
ERROR: Unable to upload scan file
```
After adding debug output, it is clear that Black Duck server responds with HTTP code 500 for unknown reason. It is also apparent that this is not related to authorization or the server since:
1. No issues running locally
2. Synopsys Detect in the same container on the same Jenkins worker doesn't have this issue.

**Comment by matthewb66** [comment]
This is obviously an environmental issue related to the software and packages available with the docker container as against a full O/S installation.

Synopsys Detect uses unrelated technology so is not relevant here.

Please confirm:
1. The utility/script version you are using
2. That you are using the latest available version
3. The Python version available both outside and inside the container
4. How you are installing the utility (using pip or running the script standalone)
5. That you are correctly using Python virtual envs
6. The Python Requests package version within the virtual env after installation

Thanks

**Comment by hikkamorii** [comment]
Yes, I understand that Detect is unrelated, just to point out the fact that it shouldn't have issues authenticating.
1. I'm using import_yocto_bm script version 2.7
3. I may not have been clear enough, but I ran script inside docker container in both cases, the difference being that whether this docker container is ran on my machine, or on Jenkins, so both use same packages.
4. I installed it standalone
5. I don't use virtualenv
6. Inside both docker containers requests 2.28.1 is installed.

**Comment by matthewb66** [comment]
There still isn't enough information to determine what's going on.
Clearly there is something different between the containers/environments as
otherwise the issue would not exist.

The script uses standard python packages so it is highly likely that there
is a comms error in 1 environment, potentially a proxy or certificate issue
which is not exposed by Synopsys Detect. Again I have no information on how
you are configuring Synopsys Detect so this doesn't help.

The utility is provided under OSS licensing without warranty or liability
(and not covered by standard support), so the right (only) approach here is
for you to debug what is going on in your environment. I suggest adding
some debug statements and running as a script.

For future comms on this, please email me at ***@***.***
Please also confirm in the email which organisation you work for, and your
current Black Duck license information.

Thanks
