### ISSUE TITLE
bitbake-layers has to be executed in correct directory

### ISSUE THREAD

**Issue by arnemertz** [blackducksoftware/import_yocto_bm#5]
If we call the script from an arbitrary directory and provide the `-y` parameter but do not provide the `--bblayers_out` parameter, the script calls bitbake-layers from the working directory instead of the yocto build directory and then fails (Command '['bitbake-layers', 'show-recipes']' returned non-zero exit status).

https://github.com/blackducksoftware/import_yocto_bm/blob/80c8b2d0fdf0c43c3e6f73aa4536ead4b3026d1c/import_yocto_bm/process.py#L46-L50

**Comment by matthewb66** [comment]
Another good catch - I will update in v2.2 shortly

**Comment by matthewb66** [comment]
Actually this issue is not reproducible.
The command 'bitbake-layers' can be run from any location provided the OE environment has been set prior to calling it.

So the correct flow is either:
1. Set the OE environment before running the import_yocto_bm utility OR
2. Specify the OE env file in wizard mode - which will set the environment before calling bitbake-layers.

No further action needed
